# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Bruno writes software"
description: > # this means to ignore newlines until "email:"
   Breaking fast and moving things.

email: bruno@brunoabrantes.com
#blog logo
logo: "/assets/images/logo.jpg"
# blog cover
cover: "/assets/images/cover.jpg"
cover_blurred: "/assets/images/cover_blur.jpg"

name: 'Bruno Abrantes'
author: 'Bruno Abrantes'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://brunoabrantes.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/inf0rmer
    desc: Follow me on Twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/inf0rmer
    desc:	See my code on Github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:

gems:
  - jekyll-assets
  - uglifier
  - sass
assets:
  js_compressor:  uglifier
  css_compressor: sass
source: ./_source
plugins: ./_source/_plugins
